spring:
  datasource:
    url: jdbc:h2:mem:mydb;DATABASE_TO_UPPER_CASE=false
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true